#!/usr/bin/env python3
"""Experiment B: derive compile-time phase-specialized FMOPNA_Clock functions.

Reads the single vendored source body (upstream/furnace-ym2608-lle/fmopna_impl.c)
and emits, for each phase, a compilable wrapper `.c` plus a derived `.body.c`
with the YM2608 phase pinned to a compile-time constant:

  mdp_fmopna_clock_low(fmopna_t*, int)   ->  chip->mclk1=1; chip->mclk2=0
  mdp_fmopna_clock_high(fmopna_t*, int)  ->  chip->mclk1=0; chip->mclk2=1

The ONLY changes are (a) the function name and (b) the three seed lines that
derive mclk1/mclk2 from the `clk` parameter, replaced with the pinned constants.
`clk` is used nowhere else in the body, so the emitted functions are by
construction half-edge equivalent to the reference FMOPNA_Clock(chip,{0,1}).
Nothing else is edited: no hand-maintained second implementation.

Usage: gen_phase_specialize.py <fmopna_impl.c> <out_dir>
"""
import os
import sys

PHASE_SEED = (
    "    chip->input.clk = clk;\n"
    "\n"
    "    chip->mclk1 = !chip->input.clk;\n"
    "    chip->mclk2 = chip->input.clk;"
)
SIGNATURE = "void FMOPNA_Clock(fmopna_t* chip, int clk)"


def derive(src: str, name: str, pin_mclk1: int, pin_mclk2: int) -> str:
    assert src.count(PHASE_SEED) == 1, ("seed not unique", src.count(PHASE_SEED))
    assert src.count(SIGNATURE) == 1
    out = src.replace(
        PHASE_SEED,
        f"    chip->input.clk = {pin_mclk2};\n"
        f"\n"
        f"    chip->mclk1 = {pin_mclk1};\n"
        f"    chip->mclk2 = {pin_mclk2};",
    ).replace(SIGNATURE, f"void {name}(fmopna_t* chip, int clk)")
    return out


DISPATCH_DEF = {
    "mdp_fmopna_clock_low": (1, 0),
    "mdp_fmopna_clock_high": (0, 1),
}
HEADER_TMPL = (
    "/* Auto-generated by tools/gen_phase_specialize.py.\n"
    " * Compile-time phase-specialized YM2608 clock ({name}). The ONLY edits\n"
    " * versus the vendored body are the function name and the three seed lines\n"
    " * deriving mclk1/mclk2 from the phase; everything else is unchanged, so\n"
    " * this function is by construction half-edge equivalent to\n"
    " * FMOPNA_Clock(chip, {phase}).\n"
    " * SPDX-License-Identifier: GPL-2.0-or-later\n"
    " */\n"
    "/* Derived body (concrete, identical bytes to the vendored core except the\n"
    " * name + phase seeds). Included as a sibling file. */\n"
    "#define FMOPNA_YM2608\n"
    "#include \"{name}.body.c\"\n"
)


def main() -> None:
    if len(sys.argv) != 3:
        print(__doc__)
        sys.exit(2)
    src = sys.argv[1]
    data = open(src, encoding="utf-8").read()
    out_dir = sys.argv[2]
    os.makedirs(out_dir, exist_ok=True)
    for name, (m1, m2) in DISPATCH_DEF.items():
        body = derive(data, name, m1, m2)
        # Emit a wrapper TU that defines FMOPNA_YM2608 then includes the
        # derived body, exactly as upstream's fmopna_2608.c does for the core.
        wrapper = HEADER_TMPL.format(name=name, phase=m2)
        # Write derived body to its own file so the include is unambiguous.
        body_path = os.path.join(out_dir, name + ".body.c")
        open(body_path, "w", encoding="utf-8").write(body)
        # Write the compilable wrapper next to it.
        open(
            os.path.join(out_dir, name + ".c"), "w", encoding="utf-8"
        ).write(wrapper)
    print("wrote", out_dir + "/mdp_fmopna_clock_{low,high}.{c,body.c}")
    print("only changes: function name + 3 phase-seed lines; body otherwise identical")


if __name__ == "__main__":
    main()
