#!/usr/bin/env python3
"""Experiment C: derive a fixed-prescaler-specialized FMOPNA_Clock.

The prescaler selects (write register 0x2d) drive two `switch (prescaler_sel)`
blocks that choose the master-clock-dividing formulas. In a typical render the
select is set once (commonly 0) and does not change, so specializing for a
fixed select collapses both switches to their single selected case and lets the
compiler drop the other cases' code.

This emits `mdp_fmopna_clock_fixedpresc(fmopna_t*, int)`, derived from the SAME
vendored `fmopna_impl.c`. The only changes are:
  * the function name, and
  * the two `switch (chip->prescaler_sel[1]) { ... }` blocks are replaced by
    the body of their selected `case N:` arm (guarded to execute regardless of
    select). `--select N` picks the arm; the default (2) is the value the
    adapter's session path takes on IC reset and for the cached Furnace default
    prescaler program.
Everything else is byte-identical, so the emitted function is equivalent to the
reference **for renders that keep the prescaler select at N**. It is an
opt-in, experiment-only artifact and never ships; a render that changes the
select would not be bit-exact, so callers must pin the select to N.

Usage: gen_fixed_prescaler.py <fmopna_impl.c> <out.json_or_dir>
"""
import os
import re
import sys

FUNC_SIG = "void FMOPNA_Clock(fmopna_t* chip, int clk)"
SWITCH_RE = re.compile(
    r"switch \(chip->prescaler_sel\[1\]\)\s*\{.*?\n\s*\}",
    re.S,
)


def _case0_body(switch_txt: str, n: int) -> str:
    m = re.search(rf"case {n}:\n(.*?)\n\s+break;", switch_txt, re.S)
    if not m:
        raise AssertionError(f"no case {n} arm in switch block")
    # re-indent the case-n body to the switch's indent level.
    body = m.group(1)
    lines = [ln[4:] if ln.startswith("    ") else ln for ln in body.split("\n")]
    return "\n".join(lines)


def derive(src: str, fixed_select: int = 2, name: str = "mdp_fmopna_clock_fixedpresc") -> str:
    assert src.count(FUNC_SIG) == 1
    out = src.replace(FUNC_SIG, f"void {name}(fmopna_t* chip, int clk)")
    switches = list(SWITCH_RE.finditer(out))
    assert len(switches) == 2, f"expected 2 switch blocks, found {len(switches)}"
    for sw in sorted(switches, key=lambda m: -m.start()):
        block = sw.group(0)
        body = _case0_body(block, fixed_select)
        out = out[: sw.start()] + body + out[sw.end() :]
    return out


def main() -> None:
    args = sys.argv[1:]
    fixed_select = 2  # IC-reset default in the adapter's session path
    if args and args[0] == "--select":
        fixed_select = int(args[1])
        args = args[2:]
    if len(args) != 2:
        print(__doc__)
        sys.exit(2)
    src, out_dir = args
    data = open(src, encoding="utf-8").read()
    body = derive(data, fixed_select=fixed_select)
    os.makedirs(out_dir, exist_ok=True)
    open(os.path.join(out_dir, "mdp_fmopna_clock_fixedpresc.body.c"), "w", encoding="utf-8").write(body)
    wrapper = (
        "/* Auto-generated by tools/gen_fixed_prescaler.py: fixed-prescaler\n"
        " * (select={n}) specialization of FMOPNA_Clock. Only the function name + two\n"
        " * prescaler switch blocks change (each replaced by its select={n} arm body).\n"
        " * Experiment C; opt-in, never ships. SPDX-License-Identifier: GPL-2.0-or-later\n"
        " */\n"
        "#define FMOPNA_YM2608\n"
        "#include \"mdp_fmopna_clock_fixedpresc.body.c\"\n"
    ).format(n=fixed_select)
    open(os.path.join(out_dir, "mdp_fmopna_clock_fixedpresc.c"), "w", encoding="utf-8").write(wrapper)
    print("wrote", out_dir + "/mdp_fmopna_clock_fixedpresc.{c,body.c}")
    print(f"specialized for prescaler select = {fixed_select} (only function name + 2 switch blocks changed)")


if __name__ == "__main__":
    main()
