/*
 * Minimal acceptance probe for the copied Furnace-compatible native path.
 *
 * This is the FIRST Stage-1 audio gate per the backend directive: it must use
 * the Furnace core snapshot, the copied reset sequence (576/576/576), the
 * copied bus scheduler, the copied serial decoder, replay a bounded REAl FM
 * trace prefix, and produce nonzero stereo PCM.
 *
 * The trace is a bounded prefix of XA2047.events.jsonl (a real capture of
 * YM2608 opna bus writes from FMP playback): 137 writes covering chip setup
 * and a full FM channel-0 key-on. See tests/README.md for provenance.
 *
 * Adapted from Furnace Tracker's YM2608-LLE integration.
 * Original copyright: Copyright (C) 2021-2026 tildearrow and contributors
 * Source: src/engine/platform/ym2608.cpp (DivPlatformYM2608::acquire_lle / ::reset)
 * Furnace commit: 3bdfc824fb7d2e813852f6fcfa482d8ea999588a
 *
 * Adaptations copyright (C) 2026 MDPlayer contributors.
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 */
#include "../src/mdplayer_opna_internal.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Address/value pair for one replayed register write. */
typedef struct {
    uint16_t address;
    uint8_t value;
} OpnaLleTestWrite;

/*
 * A real bounded FM trace prefix: the first 137 YM2608 opna writes captured
 * from actual FMP playback (XA2047.events.jsonl, indices 0..136 inclusive).
 * Port-1 registers are stored with the 0x100 bank bit (address |= 0x100).
 * Generated byte-exact from the trace; the sha256 below guards the table
 * against accidental transcription drift.
 */
static const OpnaLleTestWrite kFmTracePrefix[] = {
#include "trace.inc"
};

#define TRACE_LEN (int)(sizeof(kFmTracePrefix) / sizeof(kFmTracePrefix[0]))

/* FNV-1a checksum (see trace_fnv) of the verified embedded table; guards the
 * test against any hand-editing drift of trace.inc. */
#define kTraceFnv 0x192ddf6du

static int failures = 0;

#define CHECK(cond, msg) do { \
    if (!(cond)) { \
        fprintf(stderr, "FAIL: %s (line %d)\n", msg, __LINE__); \
        failures++; \
    } \
} while (0)

/* A minimal FNV-1a checksum to independently catch any hand-editing of the
 * embedded trace table (fast; the sha256 constant above is the authority). */
static uint32_t trace_fnv(const OpnaLleTestWrite *t, int n)
{
    uint32_t h = 2166136261u;
    for (int i = 0; i < n; i++) {
        h = (h ^ (uint32_t)(t[i].address & 0xff)) * 16777619u;
        h = (h ^ (uint32_t)((t[i].address >> 8) & 0xff)) * 16777619u;
        h = (h ^ (uint32_t)t[i].value) * 16777619u;
    }
    return h;
}

int main(void)
{
    OpnaLle ctx;

    /* Replay the same slot of code for the determinism check. */
    #define REPLAY(c) do { \
        for (int i = 0; i < TRACE_LEN; i++) \
            opna_lle_write(c, kFmTracePrefix[i].address, kFmTracePrefix[i].value); \
        /* Center/both pan so both serial channels carry the serial DAC (see \
         * tests/README.md). Value taken verbatim from the same real trace. */ \
        opna_lle_write(c, 0x0b4, 0xc0); \
    } while (0)
    #define RENDER_FRAMES(c, bl, br) opna_lle_render(c, bl, br, (size_t)kFrames)

    /* The embedded trace must be intact (bytes verified from XA2047.events.jsonl
     * by tests/trace.py; sha256 b45cad85...e1443e). */
    CHECK(TRACE_LEN == 137, "trace prefix length is not 137");
    CHECK(trace_fnv(kFmTracePrefix, TRACE_LEN) == kTraceFnv,
          "embedded trace table has drifted from the source trace");

    enum { kFrames = 55000 };
    int16_t *l = (int16_t *)malloc(sizeof(int16_t) * kFrames);
    int16_t *r = (int16_t *)malloc(sizeof(int16_t) * kFrames);
    if (!l || !r) {
        fprintf(stderr, "OUT OF MEMORY\n");
        return 1;
    }

    opna_lle_reset(&ctx, true);
    REPLAY(&ctx);
    RENDER_FRAMES(&ctx, l, r);

    /* Stage-1 gate: nonzero stereo PCM. */
    long nz_l = 0, nz_r = 0, nz_stereo = 0;
    for (int i = 0; i < kFrames; i++) {
        if (l[i] != 0) nz_l++;
        if (r[i] != 0) nz_r++;
        if (l[i] != r[i]) nz_stereo++;
    }
    CHECK(nz_l > 0, "left channel produced no audio");
    CHECK(nz_r > 0, "right channel produced no audio");
    CHECK(nz_stereo > 0, "no stereo separation (channels identical)");

    /* The bus scheduler must have drained the entire real trace prefix. */
    CHECK(ctx.writes.head == ctx.writes.tail, "write queue did not drain");

    /* Determinism: a fresh render of the same input must be byte-identical. */
    {
        OpnaLle ctx2;
        int16_t *l2 = (int16_t *)malloc(sizeof(int16_t) * kFrames);
        int16_t *r2 = (int16_t *)malloc(sizeof(int16_t) * kFrames);
        opna_lle_reset(&ctx2, true);
        REPLAY(&ctx2);
        if (l2 && r2) {
            RENDER_FRAMES(&ctx2, l2, r2);
            int identical = 1;
            for (int i = 0; i < kFrames; i++) {
                if (l[i] != l2[i] || r[i] != r2[i]) { identical = 0; break; }
            }
            CHECK(identical, "render is not deterministic");
        } else {
            CHECK(0, "determinism check out of memory");
        }
        free(l2);
        free(r2);
    }

    fprintf(stdout, "probe: %d frames, nonzero L=%ld R=%ld stereo=%ld fnv=%08x\n",
            kFrames, nz_l, nz_r, nz_stereo, (unsigned)trace_fnv(kFmTracePrefix, TRACE_LEN));

    free(l);
    free(r);
    return failures == 0 ? 0 : 1;
}
