#!/usr/bin/env python3
"""Regenerate tests/furnace_reference_fixture.c.

The fixture is a bounded real YM2608 OPNA bus-write trace checked into the
test project. It is generated from XA2047.events.jsonl (a real capture of
YM2608 `opna` bus writes recorded from actual FMP playback) and records, per
write: absolute master clock, bank (port select), register and value.

ABSOLUTE MASTER CLOCK (FIxture-GENERATION ONLY):
The source trace stores each write on a sample timeline (`sample`). The
production timing path later drives the chip in native master-clock pairs and
does NOT use this sample-derived clock. This temporary conversion is applied
only to record a plausible absolute clock in the checked-in fixture and is
explicitly documented as fixture generation only:
    master_clock = sample * (YM2608 master clock / sample rate)
with master clock = 8 MHz and sample rate = 44.1 kHz (181 clocks/sample).

Run:  python3 tests/gen_furnace_reference_fixture.py
      (from MDPlayer/native/MDPlayer.OpnaNative)
"""
import json
import os
import sys

MASTER_CLK = 8000000
SAMPLE_RATE = 44100
CLK_PER_SAMPLE = MASTER_CLK // SAMPLE_RATE

THIS_DIR = os.path.dirname(os.path.abspath(__file__))


def main():
    trace_path = os.path.abspath(os.path.join(THIS_DIR, "../../../../XA2047.events.jsonl"))
    out_path = os.path.join(THIS_DIR, "furnace_reference_fixture.c")

    events = []
    with open(trace_path) as f:
        for ln in f:
            ln = ln.strip()
            if not ln:
                continue
            d = json.loads(ln)
            if d.get("ev") == "opna":
                events.append(d)

    # Bounded prefix: indices 0..136 inclusive (the same real prefix the
    # original probe replays, covering chip setup + a full FM key-on).
    bound = events[0:137]

    with open(out_path, "w") as f:
        f.write("/*\n")
        f.write(" * Real Furnace YM2608-LLE reference trace fixture.\n")
        f.write(" *\n")
        f.write(" * A bounded real YM2608 OPNA bus-write trace checked into the\n")
        f.write(" * test project, generated from XA2047.events.jsonl (a real capture\n")
        f.write(" * of YM2608 `opna` writes from FMP playback). Generated by\n")
        f.write(" * tests/gen_furnace_reference_fixture.py. Do not edit by hand.\n")
        f.write(" *\n")
        f.write(" * The absolute master clock is a TEMPORARY fixture-only conversion\n")
        f.write(" * from the source trace's sample timeline (sample * 181, at 8 MHz /\n")
        f.write(" * 44.1 kHz). The production timing path does not use it. See the\n")
        f.write(" * generator script header for the documented conversion.\n")
        f.write(" *\n")
        f.write(" * Adapted from Furnace Tracker's YM2608-LLE integration.\n")
        f.write(" * Original copyright: Copyright (C) 2021-2026 tildearrow and contributors\n")
        f.write(" * Source: src/engine/platform/ym2608.cpp\n")
        f.write(" * Furnace commit: 3bdfc824fb7d2e813852f6fcfa482d8ea999588a\n")
        f.write(" *\n")
        f.write(" * Adaptations copyright (C) 2026 MDPlayer contributors.\n")
        f.write(" *\n")
        f.write(" * SPDX-License-Identifier: GPL-2.0-or-later\n")
        f.write(" */\n")
        f.write("#include <stdint.h>\n\n")
        f.write("typedef struct {\n")
        f.write("    uint64_t master_clock;   /* absolute native time (pairs); fixture-only */\n")
        f.write("    int bank;                /* OPNA port select: 0 = bank A0, 1 = bank A1 */\n")
        f.write("    int reg;                 /* register address (0x00..0xff)              */\n")
        f.write("    int value;               /* data byte                                  */\n")
        f.write("} OpnaFurnaceRefWrite;\n\n")
        f.write("static const OpnaFurnaceRefWrite kFurnaceRefWrites[] = {\n")
        for e in bound:
            bank = 1 if e.get("port") == 1 else 0
            mc = e.get("sample", 0) * CLK_PER_SAMPLE
            f.write("    {%d, %d, 0x%02x, 0x%02x},\n" % (mc, bank, e["address"] & 0xff, e["data"] & 0xff))
        f.write("};\n\n")
        f.write("static const int kFurnaceRefWriteCount = %d;\n" % len(bound))

    print("wrote %d writes to %s" % (len(bound), out_path))
    return 0


if __name__ == "__main__":
    sys.exit(main())
